### ISSUE TITLE
Support for upgrading already installed packages

### ISSUE THREAD

**Issue by brcolow** [svnpenn/sage#1]
It would be really nice to be able to upgrade already installed packages to their most recent versions.

For example:
`sage upgrade bash` or `sage upgrade --all`

apt itself has this functionality, as does pacman, and some other package managers I know of. It is for me a really crucial feature as it would allow one to keep installed packages up to date.

For example, say one does `sage install git` which installs git version 2.7.0. Some time later, git 2.8.0 is released. When it is available in the cygwin package listings, running `sage upgrade git` would see that 2.8.0 is now out, and so would then remove 2.7.0 and install 2.8.0.

(As requested in https://github.com/transcode-open/apt-cyg/issues/22)

**Comment by svnpenn** [comment]
@brcolow thanks for the issue. This will be fixed this week.

**Comment by brcolow** [comment]
How does one use the new `--upgrade` argument to upgrade all installed packages after update?

**Comment by svnpenn** [comment]
sage update
    sage list | xargs sage install --upgrade

**Comment by brcolow** [comment]
Do you plan to support that checking if a new version is available? That would make a swell addition to this functionality IMHO.

**Comment by svnpenn** [comment]
It is trivial to implement, however I am still in the middle of a federal copyright case on the original repo. Remind me in a week and I can probably knock it out

**Comment by svnpenn** [comment]
@brcolow check new version

**Comment by svnpenn** [comment]
@brcolow check new version, works like this:

    sage update
    sage list | xargs sage install

**Comment by svnpenn** [comment]
@brcolow check new version, *--upgrade* option not required:

    sage update
    sage list | xargs sage install

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/14
