### ISSUE TITLE
install --upgrade issue

### ISSUE THREAD

**Issue by brianmorton** [svnpenn/sage#12]
`$ sage install --upgrade rsync`
`/usr/bin/sage: line 433: [: -v: unary operator expected`

Seems to go on to complete the upgrade/reinstall anyway:
```
Installing rsync
rsync-3.0.9-1.tar.bz2: OK
Unpacking...
Package rsync requires the following packages, installing:
libgcc1 libiconv2 cygwin
Package libgcc1 is already installed, skipping
Package libiconv2 is already installed, skipping
Package cygwin is already installed, skipping
Package rsync installed
```

**Comment by svnpenn** [comment]
This is likely a dup from the old repo, which is down otherwise I would link to it. If you can demonstrate that you have an up to date Bash, I will reopen

**Comment by brianmorton** [comment]
Based on the developments in issue #1 it seems like this is a bit moot now.

I do not, at this moment, have access to the cygwin environment where I experienced the issue, and therefore am unsure of the bash version. For posterity, it was whatever came with the cygwin install (installed fresh in the last few months).

**Comment by svnpenn** [comment]
Yes, this was fixed with http://github.com/svnpenn/sage/commit/78ea516aaa271543d3f2dc25d705dd509a18f7d3. `[ -v ]` is not POSIX, so I decided to remove it. Side note, posting an issue then going AFK for 8 days is a good way to:

1. piss off the dev
2. get the issue closed
3. get yourself blocked
