### ISSUE TITLE
What is the license for sage?

### ISSUE THREAD

**Issue by jat255** [svnpenn/sage#13]
I see there is some previous issues about this that were not suitably answered. I don't wish to cause any issues, but as a FOSS supporter, I want to ensure that I'm using open-source software as much as I can. Is there a license for sage, and if so, is it open source? I believe Github's default is All Rights Reserved, no?

**Comment by svnpenn** [comment]
TBH I do not care about that stuff. Tell me what works and I can probably add it

**Comment by svnpenn** [comment]
I am not going to deal with people who post an issue then ignore me for 2 days. get your shit together and i will reopen

**Comment by jat255** [comment]
Wow, 1 day before you start slinging insults? I can see why your collaborators loved working with you. I would suggest reconsidering your attitude. Enjoy your stolen project...

**Comment by svnpenn** [comment]
@jat255 has been permabanned for rude comments. If someone else wishes to open a duplicate that is acceptable
