### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by idarlund** [svnpenn/sage#14]
Feature request; sage upgrade. Upgrade all installed packages.

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/1

**Comment by svnpenn** [comment]
As can be seen in the previous issue, this is already possible. In the future, you would do well to utilitze the *Search This repository* feature.

    sage update
    sage list | xargs sage install

**Comment by idarlund** [comment]
This will reinstall all packages and not only the ones that need to be updated.

**Comment by svnpenn** [comment]
No

~~~
$ sage list | xargs sage install
Installing libpopt0
libpopt0-1.16-1.tar.xz: OK
Unpacking...
~~~

**Comment by idarlund** [comment]
my bad, there was a lot of actual updates :)

**Comment by svnpenn** [comment]
@idarlund can you please star this repository?

**Comment by svnpenn** [comment]
https://github.com/transcode-open/apt-cyg/issues/74
