### ISSUE TITLE
Multi-mirror

### ISSUE THREAD

**Issue by masaeedu** [svnpenn/sage#19]
Allow installation using multiple mirrors as sources. See transcode-open/apt-cyg#19

**Comment by svnpenn** [comment]
Ok, I see this is implemented with /etc/setup/setup.rc:

~~~
last-mirror
	http://cygwin.mirror.constant.com/
	http://mirrors.metapeer.com/cygwin/
~~~

However I do not see a use for it, at least not personally. I dont use
CygwinPorts, I use Glade:

http://github.com/svnpenn/glade

and in fact do not care for CygwinPorts. Glade only requires Make:

~~~
      3,316 libcrypt0
     60,792 libgc1
    559,092 libguile17
  2,222,820 libguile2.0_22
     13,892 libltdl7
    376,256 libunistring2
    459,228 make

packages: 7
bytes: 3,695,396
~~~

Compare with CygwinPorts:

~~~
      3,388 autoconf
    204,911 autoconf2.1
    720,716 autoconf2.5
      3,043 automake
    730,203 automake1.10
    879,836 automake1.11
    750,462 automake1.12
    797,813 automake1.13
    594,916 automake1.14
    799,284 automake1.15
    253,595 automake1.4
    339,540 automake1.5
    373,724 automake1.6
    435,994 automake1.7
    510,652 automake1.8
    569,347 automake1.9
  5,233,952 binutils
    227,324 csih
    370,020 cygport
     63,280 cygrunsrv
    286,348 cygwin-devel
     27,036 diffstat
    304,600 dos2unix
 16,812,628 gcc-core
  9,981,668 gcc-g++
    664,564 lftp
      6,252 libatomic1
      4,092 libcom_err2
      3,316 libcrypt0
    884,460 libdb5.3
     70,572 libedit0
     48,024 libexpat1
     60,792 libgc1
    354,972 libgnutls28
     42,300 libgomp1
     96,268 libgssapi_krb5_2
    559,092 libguile17
  2,222,820 libguile2.0_22
    114,976 libhogweed2
     38,752 libidn11
     35,908 libidn2_0
    375,052 libisl13
     67,492 libk5crypto3
    222,032 libkrb5_3
     13,840 libkrb5support0
     13,892 libltdl7
     34,044 libmpc3
     83,008 libnettle4
    144,820 libopenldap2_4_2
     38,508 libpsl5
    130,728 libquadmath0
    131,228 libsasl2_3
    725,876 libtool
    376,256 libunistring2
      1,928 libvtv0
     12,225 lndir
    231,416 m4
    459,228 make
    767,296 openssh
    103,344 patch
  3,531,128 perl
     39,252 perl-Authen-SASL
     28,524 perl-Authen-SASL-XS
     17,492 perl-Carp
      6,992 perl-Digest-HMAC
    171,388 perl-IO-Socket-SSL
     79,384 perl-MailTools
    197,736 perl-MIME-tools
      3,416 perl-Net-SMTP-SSL
    250,492 perl-Net-SSLeay
    188,100 perl-Pod-Simple
     32,140 perl-TimeDate
     54,760 perl-Unicode-Normalize
        260 perl_autorebase
  2,951,988 perl_base
     34,980 publicsuffix-list-dafsa
    658,072 rsync
    932,776 texinfo
    190,056 unzip
  4,662,920 w32api-headers
  1,963,800 w32api-runtime
    815,176 wget
      1,244 windows-default-manifest

packages: 83
bytes: 67,225,729
~~~

Also Yaakov is a dick and ignores my issues:

- http://github.com/cygwinports/mingw64-x86_64-lua/issues/1
- http://github.com/cygwinports/mingw64-x86_64-nghttp2/issues/1
- http://github.com/cygwinports/mingw64-x86_64-pcre/issues/1
- http://github.com/cygwinports/mingw64-x86_64-expat/issues/1

The only other use case I see would be if someone has a personal mirror with
some homemade packages. This is cool, but I dont currently do that and so I dont
have a need for it. I can implement this change if the demand is there, but I
need to be convinced. In particular if you can name packages that arent on the
primary mirrors. All I have seen named so far is PHP, and that is on main
mirrors, so not sure why that guy is getting it from CygwinPorts. I am closing
this until that happens.

**Comment by masaeedu** [comment]
I am trying to use the desktop environment bundled by [the swan project](https://github.com/starlight/swan-desktop), without using their installer or package manager. The entire point of the installer seems to be to use the alternate mirror, but the package manager is broken in several ways and is not as mature as apt-cyg/sage.

**Comment by svnpenn** [comment]
@masaeedu sorry, but I do not see that you have listed a package as I have
requested. Also you waited 4 days to respond, which tells me you are not serious
about this issue.

I am permanently banning you from this repository and locking this issue. If you
would like to dispute this you can message me at svnpenn at gmail.com. If anyone
else would like this feature, they can repost it as a new issue, thanks.
