### ISSUE TITLE
How does sage compares to apt-cyg ?

### ISSUE THREAD

**Issue by Lucas-C** [svnpenn/sage#2]
I'm used to [`apt-cyg`](//github.com/transcode-open/apt-cyg). Why should I use `sage` instead ?

**Comment by svnpenn** [comment]
The apt-cyg repository has been closed by me under a DMCA takedown, likely permanently. I am seeking a court order today to assist in this. I am the sole developer for both projects so I would say the choice is clear.

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/27

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/3
