### ISSUE TITLE
Is this project related to apt-cyg?

### ISSUE THREAD

**Issue by jbduncan** [svnpenn/sage#27]
Hi @svnpenn. I understand from information online that sage is a fork of [transcode-open/apt-cyg](https://github.com/transcode-open/apt-cyg)? Can you confirm my understanding for me?

If so, could you explain to me how the two projects are related? :)

**Comment by svnpenn** [comment]
In keeping with issue 3, @jbduncan has now been permanently banned from this
repository.

I don’t want to talk about it to you or to anyone else. I’m done explaining
myself.

I would suggest you and anyone reading to utilize the search feature before
creating new issues. If you wish to communicate further I can be reached here:

~~~
svnpenn at gmail dot com
~~~

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/2

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/3
