### ISSUE TITLE
Whats the relation of this repo to apt-cyg?

### ISSUE THREAD

**Issue by mosbth** [svnpenn/sage#3]
The repo https://github.com/transcode-open/apt-cyg was closed down a couple of days ago du  to DCMA.

What is this (svnpenn/sage) repo's relation to that repo, and to the original repo from Google code?

Is there any background story to clear things up?

**Comment by mosbth** [comment]
Found the information in #2, its a bit hard to find and I can not find anything on google that tells the story.

Would be nice to know the story about this. Reading the DCMA claim, which is is anonomously presented, does not say who claimed it or why. transcode/apt-cyg was not a new repo, it had been there for a couple of years.

I just want to know whats right and wrong here. I have users who depend on my recommendation.

**Comment by svnpenn** [comment]
I didnt say it before on #2, so let me say it now: anyone that brings up the pending legal matter, including now @mosbth, gets an instant and permanent ban from this repository. I dont plan on discussing this further until the legal matter has been resolved.

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/27

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/2

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/2

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/2
