### ISSUE TITLE
install doesn't work

### ISSUE THREAD

**Issue by SSE4** [svnpenn/sage#31]
```
SSE4@DESKTOP-E3NFU1V ~
$ sage install make
x86_64/release/libgc/libcord1/libcord1-7.6.6-1.tar.xz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
x86_64/release/libgc/libcord1/libcord1-7.6.6-1.tar.xz
Anonymous login succeeded for SSE4@DESKTOP-E3NFU1V

x86_64/release/libgc/libcord1/libcord1-7.6.6-1.tar.xz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
Unpacking...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
```
SSE4@DESKTOP-E3NFU1V ~
$ sage update
x86_64/setup.xz
Anonymous login succeeded for SSE4@DESKTOP-E3NFU1V

xzdec: (stdin): Unexpected end of input
```

**Comment by waltzofwoe** [comment]
Bug in priv_webreq. If system has not curl installed, this function tries use ftp command. And this not working. Probably, you should add curl to the list of dependencies or fix fallback with ftp.

**Comment by svnpenn** [comment]
@waltzofwoe its working fine:

~~~
$ sage install gcc-core
x86_64/release/gcc/gcc-core/gcc-core-6.4.0-5.tar.xz
Anonymous login succeeded for Steven@Steven-PC
98%
x86_64/release/gcc/gcc-core/gcc-core-6.4.0-5.tar.xz: OK
Unpacking...
~~~

**Comment by waltzofwoe** [comment]
@svnpenn no, it isn't)
Let's do a little experiment
__________________________________________________
**$ sage remove curl**
Removing curl
curl package removed

**$ sage install gcc-core**
x86_64/release/gcc/gcc-core/gcc-core-7.3.0-2.tar.xz
  ᮥ waltzofwoe@pc

x86_64/release/gcc/gcc-core/gcc-core-7.3.0-2.tar.xz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
Unpacking...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**$ sage install curl**
x86_64/release/curl/curl-7.59.0-1.tar.xz: ЦЕЛ
Unpacking...

**$ sage install gcc-core**
x86_64/release/gcc/gcc-core/gcc-core-7.3.0-2.tar.xz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.2M  100 18.2M    0     0  1673k      0  0:00:11  0:00:11 --:--:-- 2241k
x86_64/release/gcc/gcc-core/gcc-core-7.3.0-2.tar.xz: OK
Unpacking...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6340  100  6340    0     0  18702      0 --:--:-- --:--:-- --:--:-- 18702
x86_64/release/gcc/libatomic1/libatomic1-7.3.0-2.tar.xz: OK
Unpacking...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59016  100 59016    0     0   124k      0 --:--:-- --:--:-- --:--:--  124k
x86_64/release/gcc/libgomp1/libgomp1-7.3.0-2.tar.xz: OK
Unpacking...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  130k  100  130k    0     0   191k      0 --:--:-- --:--:-- --:--:--  191k
x86_64/release/gcc/libquadmath0/libquadmath0-7.3.0-2.tar.xz: OK
Unpacking...

**$ gcc**
gcc: fatal error: no input files
compilation terminated.
_____________________________
Environment: Win 10 x64, cygwin x64, Sage 2.7.0

**Comment by svnpenn** [comment]
@waltzofwoe youve been blocked from this repository - i was a little annoyed on your first comment when you posted without evidence

then you post again without even formatting code blocks

if you wish to discuss i can be contacted privately at `svnpenn at gmail dot com`

**Comment by SSE4** [comment]
@svnpenn @waltzofwoe  yes, it works with curl like a charm. thanks a lot for your help!
