### ISSUE TITLE
using sage update through a proxy

### ISSUE THREAD

**Issue by techlunacy** [svnpenn/sage#33]
hi using sage i tried to update and got this error.
`$ sage update
/usr/local/bin/sage: 7: /etc/setup/setup.sh: netproxy-port=8080: not found
`

my environment does have a proxy i need to go through
assistance would be much apprecitated.

**Comment by svnpenn** [comment]
I am definitely not interested in supporting a proxy. if you can make a patch i will consider it - in the meantime i am closing this

cheers
