### ISSUE TITLE
Whats the license for sage?

### ISSUE THREAD

**Issue by mosbth** [svnpenn/sage#4]
Original license seemed to be GNU GPL v2 for apt-cyg:
https://code.google.com/archive/p/apt-cyg/

I remember apt-cyg (transcode/apt-cyg) to be MIT, but I could be mistaken, so do not take my word for it.

sage-msys2 seems to be MIT but I can not find any license information for apt-cyg now renamed to sage. What is the license for sage?

**Comment by mosbth** [comment]
Double checked and transcode/apt-cyg was also MIT, just to be sure.

**Comment by svnpenn** [comment]
I am closing this because of @mosbth transgression in #3. If someone else wishes to open a duplicate that is acceptable.
